# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>

development:
  adapter: redis
  url: redis://127.0.0.1:6379

test:
  adapter: async
